# Generated by Django 5.2.4 on 2025-07-27 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('experience', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('roadmap', models.TextField(blank=True)),
                ('submission_text', models.TextField()),
                ('is_reviewed', models.BooleanField(default=False)),
                ('expert_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
