# Generated by Django 5.2.4 on 2025-07-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expertreviewrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertreviewrequest',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expertreviewrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
