# Generated by Django 5.2.1 on 2025-06-05 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_skillcategory_techfield_subskill_skillcategory_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
                ('experience_text', models.TextField()),
                ('calculated_level', models.CharField(max_length=50)),
                ('matched_skills', models.IntegerField()),
                ('total_skills', models.IntegerField()),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
